module.exports = {
  ci: {
    collect: {
      url: ["http://localhost:5482"],
      numberOfRuns: 3,
      settings: {
        chromeFlags: "--no-sandbox --disable-dev-shm-usage --disable-gpu",
        preset: "desktop",
        throttling: {
          rttMs: 40,
          throughputKbps: 10240,
          cpuSlowdownMultiplier: 1,
          requestLatencyMs: 0,
          downloadThroughputKbps: 0,
          uploadThroughputKbps: 0,
        },
      },
    },
    assert: {
      assertions: {
        // Accessibilité - Score minimum de 90
        "categories:accessibility": ["error", { minScore: 0.9 }],

        // Règles d'accessibilité spécifiques
        "accessibility:color-contrast": "warn",
        "accessibility:document-title": "error",
        "accessibility:heading-order": "error",
        "accessibility:html-has-lang": "error",
        "accessibility:html-lang-valid": "error",
        "accessibility:image-alt": "error",
        "accessibility:input-image-alt": "error",
        "accessibility:label": "error",
        "accessibility:link-name": "error",
        "accessibility:list": "error",
        "accessibility:listitem": "error",
        "accessibility:meta-refresh": "error",
        "accessibility:meta-viewport": "error",
        "accessibility:object-alt": "error",
        "accessibility:tabindex": "error",
        "accessibility:td-headers-attr": "error",
        "accessibility:th-has-data-cells": "error",
        "accessibility:valid-lang": "error",
        "accessibility:video-caption": "warn",
        "accessibility:video-description": "warn",
        "accessibility:bypass": "error",
        "accessibility:focusable-controls": "error",
        "accessibility:focus-traps": "error",
        "accessibility:interactive-element-affordance": "error",
        "accessibility:logical-tab-order": "error",
        "accessibility:managed-focus": "error",
        "accessibility:offscreen-content-hidden": "error",
        "accessibility:use-landmarks": "error",
        "accessibility:visual-order-follows-dom": "error",
        "accessibility:duplicate-id-active": "error",
        "accessibility:duplicate-id-aria": "error",
        "accessibility:form-field-multiple-labels": "error",
        "accessibility:frame-title": "error",
        "accessibility:landmark-one-main": "error",
        "accessibility:page-has-heading-one": "error",
        "accessibility:region": "error",
        "accessibility:skip-link": "error",
        "accessibility:unique-landmark": "error",
        "accessibility:aria-allowed-attr": "error",
        "accessibility:aria-command-name": "error",
        "accessibility:aria-hidden-body": "error",
        "accessibility:aria-hidden-focus": "error",
        "accessibility:aria-input-field-name": "error",
        "accessibility:aria-meter-name": "error",
        "accessibility:aria-progressbar-name": "error",
        "accessibility:aria-required-attr": "error",
        "accessibility:aria-required-children": "error",
        "accessibility:aria-required-parent": "error",
        "accessibility:aria-roles": "error",
        "accessibility:aria-toggle-field-name": "error",
        "accessibility:aria-tooltip-name": "error",
        "accessibility:aria-treeitem-name": "error",
        "accessibility:aria-valid-attr": "error",
        "accessibility:aria-valid-attr-value": "error",
        "accessibility:aria-valid-role": "error",
        "accessibility:button-name": "error",
        "accessibility:bypass": "error",
        "accessibility:color-contrast": "warn",
        "accessibility:definition-list": "error",
        "accessibility:dlitem": "error",
        "accessibility:document-title": "error",
        "accessibility:duplicate-id-active": "error",
        "accessibility:duplicate-id-aria": "error",
        "accessibility:form-field-multiple-labels": "error",
        "accessibility:frame-title": "error",
        "accessibility:heading-order": "error",
        "accessibility:html-has-lang": "error",
        "accessibility:html-lang-valid": "error",
        "accessibility:image-alt": "error",
        "accessibility:input-image-alt": "error",
        "accessibility:label": "error",
        "accessibility:landmark-one-main": "error",
        "accessibility:link-name": "error",
        "accessibility:list": "error",
        "accessibility:listitem": "error",
        "accessibility:meta-refresh": "error",
        "accessibility:meta-viewport": "error",
        "accessibility:object-alt": "error",
        "accessibility:page-has-heading-one": "error",
        "accessibility:region": "error",
        "accessibility:skip-link": "error",
        "accessibility:tabindex": "error",
        "accessibility:td-headers-attr": "error",
        "accessibility:th-has-data-cells": "error",
        "accessibility:unique-landmark": "error",
        "accessibility:valid-lang": "error",
        "accessibility:video-caption": "warn",
        "accessibility:video-description": "warn",
      },
    },
    upload: {
      target: "temporary-public-storage",
    },
  },
};
