name: Deploy to DockerHub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy-to-dockerhub:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Install dependencies and build
        run: |
          echo "registry=https://registry.npmjs.org/" > .npmrc
          echo "@parcel:registry=https://registry.npmjs.org/" >> .npmrc
          echo "@parcel/watcher-wasm:registry=https://registry.npmjs.org/" >> .npmrc
          npm ci
          npm run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/benevoclic-web:latest
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/benevoclic-web:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/benevoclic-web:buildcache,mode=max
